name: Main NuGet Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-nuget:
    uses: kirandevops1993/NUGET-REUSABLE-/.github/workflows/nuget-reusable.yml@main
    with:
      # Restore Inputs
      solution: OrchardCore.sln
      nugetConfigPath: ./NuGet.config
      packagesDirectory: ./packages
      verbosity: detailed
      nuGetRestoreArgs: ""
      restoreMode: restore
      noCache: true
      nuGetVersion: 6.13.2
      nuGetPath: ./nuget.exe

      # Packager Inputs
      searchPattern: src/docs/OrchardCore.Docs.csproj
      outputdir: ./nupkgs
      includeSymbols: true
      versionByBuild: false
      versionEnvVar: ""
      majorVersion: 1
      minorVersion: 0
      patchVersion: 0
      configurationToPack: Release
      buildProperties: Platform="Any CPU"
      nuGetAdditionalArgs: ""
      packagesToPack: ""
      versioningScheme: ""
      includeReferencedProjects: false
      packTimezone: ""
      toolPackage: false
      basePath: ""
      verbosityPack: ""

      # Publisher Inputs
      nuGetFeedType: internal
      feedName: https://pkgs.dev.azure.com/YourOrg/_packaging/YourFeed/nuget/v3/index.json
      skipDuplicate: false

      # Custom Command Inputs
      arguments: ""

      # Command (unified)
      command: pack

    secrets:
      apiKey: ${{ secrets.AZURE_DEVOPS_PAT }}
