name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  restore:
    uses: kirandevops1993/NUGET-REUSABLE-/.github/workflows/nuget-reusable.yml@main
    with:
      command: restore
      nugetConfigPath: 
      configuration: 'Release'
      custom: true
      restoreArguments: '--interactive'
      modifyOutputPath: true
      packDirectory: './custom_pack'
      nobuild: true
      includesymbols: true
      includesource: true
      requestTimeout: '180'
      noCache: true
      restoreDirectory: './restoredir'
      verbosityRestore: 'minimal'
      sensitiveAlphanumericInfo1: 'true'
      versioningScheme: '1.0.0'
      versionEnvVar: 'BUILD_VERSION'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '3'
      buildProperties: 'CommitId=abc123'
      verbosityPack: 'detailed'
      workingDirectory: './src'

  build:
    uses: kirandevops1993/NUGET-REUSABLE-/.github/workflows/nuget-reusable.yml@main
    needs: restore
    with:
      command: build
      nugetConfigPath: 'NuGet.config'  # ✅ FIXED
      configuration: 'Release'
      custom: true
      arguments: '--configuration Release'
      restoreArguments: '--interactive'
      modifyOutputPath: true
      packDirectory: './custom_pack'
      nobuild: true
      includesymbols: true
      includesource: true
      requestTimeout: '180'
      noCache: true
      restoreDirectory: './restoredir'
      verbosityRestore: 'minimal'
      sensitiveAlphanumericInfo1: 'true'
      versioningScheme: '1.0.0'
      versionEnvVar: 'BUILD_VERSION'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '3'
      buildProperties: 'CommitId=abc123'
      verbosityPack: 'detailed'
      workingDirectory: './src'

  test:
    uses: kirandevops1993/NUGET-REUSABLE-/.github/workflows/nuget-reusable.yml@main
    needs: build
    with:
      command: test
      nugetConfigPath: 'NuGet.config'  # ✅ FIXED
      configuration: 'Release'
      custom: true
      arguments: '--collect "Code coverage"'
      testRunTitle: 'CI Test Run'
      restoreArguments: '--interactive'
      modifyOutputPath: true
      packDirectory: './custom_pack'
      nobuild: true
      includesymbols: true
      includesource: true
      requestTimeout: '180'
      noCache: true
      restoreDirectory: './restoredir'
      verbosityRestore: 'minimal'
      sensitiveAlphanumericInfo1: 'true'
      versioningScheme: '1.0.0'
      versionEnvVar: 'BUILD_VERSION'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '3'
      buildProperties: 'CommitId=abc123'
      verbosityPack: 'detailed'
      workingDirectory: './src'

  pack:
    uses: kirandevops1993/NUGET-REUSABLE-/.github/workflows/nuget-reusable.yml@main
    needs: test
    with:
      command: pack
      nugetConfigPath: 'NuGet.config'  # ✅ FIXED
      configuration: 'Release'
      custom: true
      restoreArguments: '--interactive'
      modifyOutputPath: true
      packDirectory: './custom_pack'
      nobuild: true
      includesymbols: true
      includesource: true
      requestTimeout: '180'
      noCache: true
      restoreDirectory: './restoredir'
      verbosityRestore: 'minimal'
      sensitiveAlphanumericInfo1: 'true'
      versioningScheme: '1.0.0'
      versionEnvVar: 'BUILD_VERSION'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '3'
      buildProperties: 'CommitId=abc123'
      verbosityPack: 'detailed'
      workingDirectory: './src'
