name: Main Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  dotnet-tasks:
    uses: kirandevops1993/DOTNETCORECLI-REUSABLE/.github/workflows/dotnetreusable.yml@main
    with:
      commands: |
        restore
        build
