name: Main WorkfloW

on:
  push:
    branches:
      - main

jobs:
  dotnet-tasks:
    uses: kirandevops1993/DOTNETCORECLI-REUSABLE/.github/workflows/dotnetreusable.yml@main
    strategy:
      matrix:
        task:
          - command: restore
            projects: '**/*.csproj'
            nugetConfigPath: 'NuGet.config'
            arguments: ''
            configuration: ''
            packagesToPush: ''
            custom: ''
            restoreArguments: '--force'
            testRunTitle: ''
            modifyOutputPath: ''
            packDirectory: ''
            nobuild: false
            includesymbols: false
            includesource: false
            requestTimeout: ''
            noCache: true
            restoreDirectory: './packages'
            verbosityRestore: 'normal'
            publishPackageMetadata: ''
            versioningScheme: ''
            versionEnvVar: ''
            majorVersion: ''
            minorVersion: ''
            patchVersion: ''
            buildProperties: ''
            verbosityPack: ''
            workingDirectory: ''

          - command: build
            projects: '**/*.csproj'
            nugetConfigPath: ''
            arguments: '--configuration Release'
            configuration: 'Release'
            packagesToPush: ''
            custom: ''
            restoreArguments: ''
            testRunTitle: ''
            modifyOutputPath: ''
            packDirectory: ''
            nobuild: false
            includesymbols: false
            includesource: false
            requestTimeout: ''
            noCache: false
            restoreDirectory: ''
            verbosityRestore: ''
            publishPackageMetadata: ''
            versioningScheme: ''
            versionEnvVar: ''
            majorVersion: ''
            minorVersion: ''
            patchVersion: ''
            buildProperties: ''
            verbosityPack: ''
            workingDirectory: ''

          - command: test
            projects: '**/*.csproj'
            nugetConfigPath: ''
            arguments: '--collect "Code coverage"'
            configuration: ''
            packagesToPush: ''
            custom: ''
            restoreArguments: ''
            testRunTitle: 'unittests'
            modifyOutputPath: ''
            packDirectory: ''
            nobuild: false
            includesymbols: false
            includesource: false
            requestTimeout: ''
            noCache: false
            restoreDirectory: ''
            verbosityRestore: ''
            publishPackageMetadata: ''
            versioningScheme: ''
            versionEnvVar: ''
            majorVersion: ''
            minorVersion: ''
            patchVersion: ''
            buildProperties: ''
            verbosityPack: ''
            workingDirectory: ''

          - command: pack
            projects: '**/*.csproj'
            nugetConfigPath: ''
            arguments: ''
            configuration: 'Release'
            packagesToPush: ''
            custom: ''
            restoreArguments: ''
            testRunTitle: ''
            modifyOutputPath: './customoutput'
            packDirectory: './nupkgs'
            nobuild: true
            includesymbols: true
            includesource: true
            requestTimeout: ''
            noCache: false
            restoreDirectory: ''
            verbosityRestore: ''
            publishPackageMetadata: ''
            versioningScheme: 'continuous'
            versionEnvVar: 'PACKAGE_VERSION'
            majorVersion: '1'
            minorVersion: '0'
            patchVersion: '5'
            buildProperties: ''
            verbosityPack: 'detailed'
            workingDirectory: ''

          - command: push
            projects: ''
            nugetConfigPath: ''
            arguments: ''
            configuration: ''
            packagesToPush: './nupkgs/*.nupkg'
            custom: ''
            restoreArguments: ''
            testRunTitle: ''
            modifyOutputPath: ''
            packDirectory: ''
            nobuild: false
            includesymbols: false
            includesource: false
            requestTimeout: '300'
            noCache: false
            restoreDirectory: ''
            verbosityRestore: ''
            publishPackageMetadata: ''
            versioningScheme: ''
            versionEnvVar: ''
            majorVersion: ''
            minorVersion: ''
            patchVersion: ''
            buildProperties: ''
            verbosityPack: ''
            workingDirectory: ''

    with:
      command: ${{ matrix.task.command }}
      projects: ${{ matrix.task.projects }}
      arguments: ${{ matrix.task.arguments }}
      nugetConfigPath: ${{ matrix.task.nugetConfigPath }}
      configuration: ${{ matrix.task.configuration }}
      packagesToPush: ${{ matrix.task.packagesToPush }}
      custom: ${{ matrix.task.custom }}
      restoreArguments: ${{ matrix.task.restoreArguments }}
      testRunTitle: ${{ matrix.task.testRunTitle }}
      modifyOutputPath: ${{ matrix.task.modifyOutputPath }}
      packDirectory: ${{ matrix.task.packDirectory }}
      nobuild: ${{ matrix.task.nobuild }}
      includesymbols: ${{ matrix.task.includesymbols }}
      includesource: ${{ matrix.task.includesource }}
      requestTimeout: ${{ matrix.task.requestTimeout }}
      noCache: ${{ matrix.task.noCache }}
      restoreDirectory: ${{ matrix.task.restoreDirectory }}
      verbosityRestore: ${{ matrix.task.verbosityRestore }}
      publishPackageMetadata: ${{ matrix.task.publishPackageMetadata }}
      versioningScheme: ${{ matrix.task.versioningScheme }}
      versionEnvVar: ${{ matrix.task.versionEnvVar }}
      majorVersion: ${{ matrix.task.majorVersion }}
      minorVersion: ${{ matrix.task.minorVersion }}
      patchVersion: ${{ matrix.task.patchVersion }}
      buildProperties: ${{ matrix.task.buildProperties }}
      verbosityPack: ${{ matrix.task.verbosityPack }}
      workingDirectory: ${{ matrix.task.workingDirectory }}
