name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  dotnet-tasks:
    uses: kirandevops1993/DOTNETCORECLI-REUSABLE/.github/workflows/dotnetreusable.yml@main
    strategy:
      matrix:
        task:
          - command: restore
            projects: '**/*.csproj'
            nugetConfigPath: 'NuGet.config'
            packagesToPush: ''

          - command: build
            projects: '**/*.csproj'
            arguments: '--configuration Release'
            packagesToPush: ''

          - command: test
            projects: '**/*.csproj'
            arguments: '--collect "Code coverage"'
            packagesToPush: ''

          - command: pack
            projects: '**/*.csproj'
            configuration: 'Release'
            packagesToPush: ''

          - command: push
            packagesToPush: './nupkgs/*.nupkg'

    with:
      command: ${{ matrix.task.command }}
      projects: ${{ matrix.task.projects || '' }}
      arguments: ${{ matrix.task.arguments || '' }}
      nugetConfigPath: ${{ matrix.task.nugetConfigPath || '' }}
      configuration: ${{ matrix.task.configuration || '' }}
      packagesToPush: ${{ matrix.task.packagesToPush }}
