name: .NET Main Workflow

on:
  push:
    branches:
      - main

jobs:
  dotnet-build-test-pack:
    uses: kirandevops1993/DOTNETCORECLI-REUSABLE/.github/workflows/dotnetreusable.yml@main
    with:
      projects: '**/*.csproj'
      arguments: ''
      nugetConfigPath: ''
      packagesToPack: '**/*.csproj'
      configuration: 'Release'
      nuGetFeedType: ''  # <-- THIS IS IMPORTANT to avoid "command is required" error
