name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  dotnet-tasks:
    strategy:
      matrix:
        task:
          - command: restore
            projects: '**/*.csproj'
            feedsToUse: config
            nugetConfigPath: 'NuGet.config'

          - command: build
            projects: '**/*.csproj'
            arguments: '--configuration Release'

          - command: test
            projects: '**/*.csproj'
            arguments: '--collect "Code coverage"'

          - command: pack
            packagesToPack: '**/*.csproj'
            configuration: 'Release'

          - command: push
            packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
            nuGetFeedType: external

    uses: kirandevops1993/DOTNETCORECLI-REUSABLE/.github/workflows/dotnetreusable.yml@main
    with:
      command: ${{ matrix.task.command }}
      projects: ${{ matrix.task.projects || '' }}
      arguments: ${{ matrix.task.arguments || '' }}
      feedsToUse: ${{ matrix.task.feedsToUse || '' }}
      nugetConfigPath: ${{ matrix.task.nugetConfigPath || '' }}
      packagesToPack: ${{ matrix.task.packagesToPack || '' }}
      configuration: ${{ matrix.task.configuration || '' }}
      packagesToPush: ${{ matrix.task.packagesToPush || '' }}
      nuGetFeedType: ${{ matrix.task.nuGetFeedType || '' }}
      custom: 'true'
      restoreArguments: '--interactive'
      testRunTitle: 'CI Test Run'
      modifyOutputPath: 'true'
      packDirectory: './custom_pack'
      nobuild: 'true'
      includesymbols: 'true'
      includesource: 'true'
      requestTimeout: '180'
      noCache: 'true'
      restoreDirectory: './restoredir'
      verbosityRestore: 'minimal'
      publishPackageMetadata: 'true'
      versioningScheme: 'byPrereleaseNumber'
      versionEnvVar: 'BUILD_VERSION'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '3'
      buildProperties: 'CommitId=abc123'
      verbosityPack: 'detailed'
      workingDirectory: './src'
