name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  restore:
    uses: kirandevops1993/NUGET-REUSABLE-/.github/workflows/nuget-reusable.yml@main
    with:
      command: restore
      nugetConfigPath: 'NuGet.config'
      restoreArguments: '--interactive'
      verbosityRestore: 'minimal'
      restoreDirectory: './restoredir'
      noCache: true
      versionEnvVar: 'BUILD_VERSION'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '3'
      workingDirectory: './src'

  build:
    needs: restore
    uses: kirandevops1993/NUGET-REUSABLE-/.github/workflows/nuget-reusable.yml@main
    with:
      command: build
      arguments: '--configuration Release'
      noCache: true
      versionEnvVar: 'BUILD_VERSION'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '3'
      workingDirectory: './src'

  test:
    needs: build
    uses: kirandevops1993/NUGET-REUSABLE-/.github/workflows/nuget-reusable.yml@main
    with:
      command: test
      arguments: '--collect "Code coverage"'
      testRunTitle: 'CI Test Run'
      noCache: true
      versionEnvVar: 'BUILD_VERSION'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '3'
      workingDirectory: './src'

  pack:
    needs: test
    uses: kirandevops1993/NUGET-REUSABLE-/.github/workflows/nuget-reusable.yml@main
    with:
      command: pack
      configuration: 'Release'
      packDirectory: './custom_pack'
      nobuild: true
      includesymbols: true
      includesource: true
      sensitiveAlphanumericInfo1: 'true'
      buildProperties: 'CommitId=abc123'
      versionEnvVar: 'BUILD_VERSION'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '3'
      workingDirectory: './src'
