name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  nuget-restore:
    name: NuGet Restore
    uses: kirandevops1993/NUGET-REUSABLE-/.github/workflows/nuget-reusable.yml@main
    with:
     # Restore Inputs
      solution:
        required: false
        type: string
      nugetConfigPath:
        required: false
        type: string
      packagesDirectory:
        required: true
        type: string
      verbosity:
        required: true
        type: string
      nuGetRestoreArgs:
        required: true
        type: string
      restoreMode:
        required: true
        type: string
      noCache:
        required: true
        type: boolean
      nuGetVersion:
        required: true
        type: string
      nuGetPath:
        required: true
        type: string

      # Packager Inputs
      searchPattern:
        required: true
        type: string
      outputdir:
        required: true
        type: string
      includeSymbols:
        required: true
        type: boolean
      versionByBuild:
        required: true
        type: boolean
      versionEnvVar:
        required: true
        type: string
      majorVersion:
        required: true
        type: number
      minorVersion:
        required: true
        type: number
      patchVersion:
        required: true
        type: number
      configurationToPack:
        required: true
        type: string
      buildProperties:
        required: true
        type: string
      nuGetAdditionalArgs:
        required: true
        type: string

      # Publisher Inputs
      nuGetFeedType:
        required: true
        type: string
      feedName:
        required: true
        type: string
      skipDuplicate:
        required: true
        type: boolean

    secrets:
      apiKey: ${{ secrets.AZURE_DEVOPS_PAT }}
        
  build-solution:
    name: Build Solution
    needs: nuget-restore
    uses: kirandevops1993/MS-BUILD-TASKS-REUSABLE-/.github/workflows/msbuildtasks-reusable.yml@main
    with:
      solution: .sln
      vsVersion: latest
      msbuildArgs: "/p:OutDir=$(build.stagingDirectory) /p:DeployOnBuild=false /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p: SkipInvalidConfigurationstrue /p:PackageLocation=$(udClientLocation)"
      platform: "$(BuildPlatform)"
      configuration: "$(BuildConfiguration)"
      clean: true
      maximumCpuCount: false
      restoreNugetPackages: false
      msbuildArchitecture: x86
      logProjectEvents: true
      createLogFile: false
      logFileVerbosity: "detailed"

  run-powershell-script:
    name: Run PowerShell Script
    needs: build-solution
    uses: kirandevops1993/POWERSHELL-REUSABLE-/.github/workflows/powershellreusable.yml@main
    with:
      script-path: ".github/workflows/Get-HostName.ps1"
      script-arguments: ""
      inline-script: ""
