name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nuget-restore:
    name: NuGet Restore
    uses: kirandevops1993/NUGET-REUSABLE-/.github/workflows/nuget-reusable.yml@main
     platform:
        required: true
        type: string
        default: "Any CPU"
      configuration:
        required: true
        type: string
        default: "Release"
      maxCpu:
        required: false
        type: number
        default: 8
      clean:
        required: true
        type: boolean
        default: true
      msbuildArguments:
        required: false
        type: string
        default: ""
      createLogFile:
        required: false
        type: boolean
        default: false
      logFileVerbosity:
        required: false
        type: string
        default: "detailed"

      # Packager Inputs
      searchPattern: src/docs/OrchardCore.Docs.csproj
      outputdir: ./nupkgs
      includeSymbols: true
      versionByBuild: false
      versionEnvVar: ""
      majorVersion: 1
      minorVersion: 0
      patchVersion: 0
      configurationToPack: Release
      buildProperties: Platform="Any CPU"
      nuGetAdditionalArgs: ""

      # Publisher Inputs
      nuGetFeedType: internal
      feedName: https://pkgs.dev.azure.com/YourOrg/_packaging/YourFeed/nuget/v3/index.json
      skipDuplicate: false

    secrets:
      apiKey: ${{ secrets.AZURE_DEVOPS_PAT }}

  build-solution:
    name: Build Solution
    needs: nuget-restore
    uses: kirandevops1993/MS-BUILD-TASKS-REUSABLE-/.github/workflows/msbuildtasks-reusable.yml@main
    with:
      solution: .sln
      vsVersion: latest
      msbuildArgs: "/p:OutDir=$(build.stagingDirectory) /p:DeployOnBuild=false /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p: SkipInvalidConfigurationstrue /p:PackageLocation=$(udClientLocation)"
      platform: "$(BuildPlatform)"
      configuration: "$(BuildConfiguration)"
      clean: true
      maximumCpuCount: false
      restoreNugetPackages: false
      msbuildArchitecture: x86
      logProjectEvents: true
      createLogFile: false
      logFileVerbosity: "detailed"

  run-powershell-script:
    name: Run PowerShell Script
    needs: build-solution
    uses: kirandevops1993/POWERSHELL-REUSABLE-/.github/workflows/powershellreusable.yml@main
    with:
      script-path: ".github/workflows/Get-HostName.ps1"
      script-arguments: ""
      inline-script: ""
